language:
  php:
    - '5.6'
    - '7.2'
    - '7.3'
    - '7.4'
before_script:
  - cd includes && composer install && cd ..
  - cd tests && composer install && cd ..
script:
  - phpunit tests/test-jwt-functions.php
